function getHeatmapData(filepath, filename, peaks, ...
    procruste_transformed, masks_transformed, features_transformed)

params.nBins = 30;
params.timeStep = 1;

grid = buildSpatialGrid(procruste_transformed, params.nBins);

allData = processAllMovies( ...
    procruste_transformed, ...
    masks_transformed, ...
    features_transformed, ...
    peaks, ...
    grid, ...
    params);

summary = aggregateHeatmaps(allData);

save(fullfile(filepath,'dataframes', ...
    strcat('heatmap_',filename,'.mat')), ...
    'summary','allData','grid','params');

plotHeatmaps(summary);

end