close all
clear all

%% Init
fprintf("Initializing")
%filepath = 'D:\Antonio\extrusion systematic characterisation\test';
filepath = 'D:\Nathan';
params.nBins = 30;
params.timeStep = 1;
params.frameRate = 5;

timeDataframe = readtable( ...
    fullfile(filepath,'dataframes','timeAlignment.xlsx'));

%% Alignment choice
[selectedColumn, selectedLandmarks] = askAlignmentMethod();

[nf_extrusions,nf_divisions,nf_masks,nf_piv,nf_features] = ...
    loadFileLists(filepath);

nf_landmarks = dir( ...
    fullfile(filepath,'input',selectedLandmarks,'*landmarks.zip'));

filenames = {nf_extrusions.name};

%% Time table
timeTable = buildTimeTable(timeDataframe, selectedColumn);

%% Preprocessing 
matFile = fullfile(filepath,'dataframes', ...
    sprintf('rawData_%sAlignment.mat', selectedLandmarks));

if ~exist(matFile,'file')
    [rawData,Rglobal] = runPreprocessing(filepath, nf_extrusions,nf_divisions, nf_masks,nf_piv, nf_features, nf_landmarks, timeTable, params.frameRate, selectedLandmarks);
    save(matFile, 'rawData','Rglobal', '-v7.3');
else
    load(matFile);
end

%% Spatio-temporal binning pipeline
dataFile = fullfile(filepath, 'dataframes', ...
    sprintf('binnedData_%sAlignment_%dSpatialBins_%ghTimeStep.mat', selectedLandmarks,params.nBins, params.timeStep));

if ~exist(dataFile,'file')

    % Spatial grid
    spatialGrid.nBins = params.nBins;

    spatialGrid.xEdges = linspace( ...
        1, ...
        Rglobal.ImageSize(2), ...
        params.nBins+1);

    spatialGrid.yEdges = linspace( ...
        1, ...
        Rglobal.ImageSize(1), ...
        params.nBins+1);

    % run spatio-temporal binning
    [binnedData,summary] = runSpatioTemporalEventPipeline( ...
        filepath,...
        params,...
        rawData,...
        spatialGrid);

    save(dataFile, 'summary','binnedData','params','spatialGrid','-v7.3');
else
    load(dataFile);
end

%% Classify movies in females/males/all
    sexList = {'F','M','all'};

for iSex = 1:length(sexList) %Pour males & Femelles
 
    currentSex = sexList{iSex};

    fprintf('\n=====================\n');
    fprintf('Processing %s\n', currentSex);
    fprintf('=====================\n');

    % Select movies of the current sex
    if strcmp(currentSex,'all')
        idxSex = true(height(timeDataframe),1); %"true true false etc..." Tout les films
    else
        idxSex = strcmp(timeDataframe.sex, currentSex); %vecteur "true true false etc..." F ou M
    end

    selectedNames = erase( ...
        string(timeDataframe.Name(idxSex)), ...
        ".mat"); %Selectionne juste F ou M


    keepMovies = false(1,length(filenames));

    for k = 1:length(selectedNames)
        keepMovies = keepMovies | ...
            contains(string(filenames), selectedNames(k));
    end

    %% Global and regional analyses

    % Extrusions

    processRegionalEventData( ...
        filepath,...
        filenames,...
        [selectedLandmarks '_' currentSex '_'],...
        rawData.extrusions_transformed,...
        binnedData,...
        Rglobal,...
        summary,...
        params,...
        'extrusions',...
        keepMovies,...
        selectedLandmarks)

    % Divisions

    processRegionalEventData( ...
        filepath,...
        filenames,...
        [selectedLandmarks '_' currentSex '_'],...
        rawData.divisions_transformed,...
        binnedData,...
        Rglobal,...
        summary,...
        params,...
        'divisions',...
        keepMovies, ...
        selectedLandmarks)
end
%% PLOTS


%% Curent sex here = "all" so figures are these for all

% extrusions
plotEventsQualityControl( ...
    binnedData, ...
    filenames, ...
    rawData.landmarks_transformed, ...
    spatialGrid, ...
    'extrusions', ...
    currentSex, ...
    filepath)


plotEvents( ...
    filenames, ...
    rawData.extrusions_transformed, ...
    rawData.landmarks_transformed);

% divisions
plotEventsQualityControl( ...
    binnedData, ...
    filenames, ...
    rawData.landmarks_transformed, ...
    spatialGrid, ...
    'divisions',...
    currentSex, ...
    filepath)

plotEvents( ...
    filenames, ...
    rawData.extrusions_transformed, ...
    rawData.landmarks_transformed);

plotHeatmaps(summary, currentSex, filepath)

