function [allData,summary,params]=runSpatioTemporalEventPipeline(filepath, filenames,params, data,sex_icon)

extrusions_transformed= data.extrusions_transformed;
divisions_transformed= data.divisions_transformed; 
landmarks_transformed=data.landmarks_transformed;
masks_transformed=data.masks_transformed;
masks_relativeTime = data.masks_relativeTime;
features_transformed=data.features_transformed;

%% Processing (Spatio Temporal discretisation)

[allData,timeBins] = processAllMovies( ...
    extrusions_transformed, ...
    divisions_transformed, ... 
    masks_transformed, ...
    masks_relativeTime, ...
    features_transformed, ...
    spatialGrid, ...
    params);

%% Summary

summary = aggregateHeatmaps(allData);

save(fullfile(filepath,'dataframes', ...
    strcat('STdata_',alignMethod,'_',num2str(params.timeStep),'h_timeStep.mat')), ...
    'summary','allData','spatialGrid','params');

%% Valid Bin Mask

nMovies = size(allData,1);
nTimeBins = size(allData,2);

validBinsMovie = false(params.nBins, params.nBins, nTimeBins, nMovies);

for m = 1:nMovies
    for t = 1:nTimeBins

        d = allData{m,t};

        if isstruct(d) && isfield(d,'tissue') && ...
                isfield(d.tissue,'validBinMask') && ...
                ~isempty(d.tissue.validBinMask)

            validBinsMovie(:,:,t,m) = d.tissue.validBinMask;
        end

    end
end


%% PLOTS pour DIVISIONS aussi

%plotExtrusionsQualityControl(allData,filenames,landmarks_transformed,spatialGrid, 'extrusions')
%plotExtrusions(filenames,extrusions_transformed,landmarks_transformed);

%plotExtrusionsQualityControl(allData,filenames,landmarks_transformed,spatialGrid, 'divisions')

plotEventsQualityControl( ...
    allData, ...
    filenames, ...
    landmarks_transformed, ...
    spatialGrid, ...
    'extrusions', ...
    sex_icon, ...
    filepath)


plotEvents( ...
    filenames, ...
    extrusions_transformed, ...
    landmarks_transformed);

%Division
plotEventsQualityControl( ...
    allData, ...
    filenames, ...
    landmarks_transformed, ...
    spatialGrid, ...
    'divisions',...
    sex_icon, ...
    filepath)

plotEvents( ...
    filenames, ...
    extrusions_transformed, ...
    landmarks_transformed);

plotHeatmaps(summary, sex_icon, filepath)

end