function allData = processAllMovies( ...
    procruste_transformed, masks_transformed, features_transformed, ...
    peaks, grid, params)

movies = unique(procruste_transformed(:,3));
nMovies = max(movies);

timeBins = floor(min(procruste_transformed(:,4))):params.timeStep: ...
           ceil(max(procruste_transformed(:,4))) + params.timeStep;

allData = cell(nMovies, length(timeBins)-1);

for m = 1:nMovies
    for t = 1:length(timeBins)-1

        allData{m,t} = processMovieTimeBin( ...
            m, t, timeBins, ...
            procruste_transformed, ...
            masks_transformed, ...
            features_transformed, ...
            peaks, grid);

    end
end
end