function [allData,timeBins] = processAllMovies( ...
    extrusions_transformed, divisions_transformed, masks_transformed, masks_relativeTime, features_transformed, ...
    grid, params)

movies = unique(extrusions_transformed(:,4));
nMovies = max(movies);

timeBins = floor(min(extrusions_transformed(:,3))):params.timeStep: ...
           ceil(max(extrusions_transformed(:,3))) + params.timeStep;

allData = cell(nMovies, length(timeBins)-1);

for m = 1:nMovies
    for t = 1:length(timeBins)-1

        allData{m,t} = processMovieTimeBin( ...
            m, t, timeBins, ...
            extrusions_transformed, ...
            divisions_transformed, ... %rajout division
            masks_transformed, ...
            masks_relativeTime, ...
            features_transformed, ...
            grid);

    end
end
end